version: "3.8"

services:
  reverse-proxy:
    image: traefik:3.0@sha256:6e35da09542bf9a12712337f713cc65cfb74c8670c4cf77781fe0edd25fb7699
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  platformatic-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.platformatic-app.rule=Host(`platformatic-app.local`)"
      - "traefik.http.services.platformatic-app.loadbalancer.server.port=3042"
    volumes:
      - ./data:/app/.platformatic/data
    environment:
      PORT: 3042
      PLT_SERVER_HOSTNAME: 0.0.0.0
      PLT_SERVER_LOGGER_LEVEL: debug
      DATABASE_URL: sqlite:///app/.platformatic/data/movies.sqlite
