version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/.platformatic/data
    environment:
      PORT: 3042
      PLT_SERVER_HOSTNAME: 127.0.0.1
      PLT_SERVER_LOGGER_LEVEL: debug
      DATABASE_URL: sqlite:///app/.platformatic/data/movies.db
