version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.1@sha256:3f92eba47bd4bfda91d47b72d16fef2d7ae15db61a92b2057cf0cb389f8938f6
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  platformatic-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.platformatic-app.rule=Host(`platformatic-app.local`)"
      - "traefik.http.services.platformatic-app.loadbalancer.server.port=3042"
    volumes:
      - ./data:/app/.platformatic/data
    environment:
      PORT: 3042
      PLT_SERVER_HOSTNAME: 0.0.0.0
      PLT_SERVER_LOGGER_LEVEL: debug
      DATABASE_URL: sqlite:///app/.platformatic/data/movies.sqlite
