name: Deploy Platformatic application to the cloud
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
      - name: Checkout application project repository
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Download deps
        run: pnpm install
      - name: Run build
        run: pnpm run build
        env:
          DATABASE_URL: sqlite://.platformatic/data/db.sqlite
          PLT_SERVER_LOGGER_LEVEL: info
          PORT: 3042
          PLT_SERVER_HOSTNAME: 127.0.0.1
      - name: Deploy app
        id: deploy-app
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ vars.PLATFORMATIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
          post_pr_comment: true
        env:
          DATABASE_URL: sqlite://.platformatic/data/db.sqlite
          PLT_SERVER_LOGGER_LEVEL: info
          PORT: 3042
          PLT_SERVER_HOSTNAME: 127.0.0.1

      - name: Output deployed app URL
        run: echo '${{ steps.deploy-app.outputs.platformatic_app_url }}'
